runtime: go122 # Or your desired Go version (e.g., go1.21, go1.20)
# instance_class: F1 # Optional: default is F1, adjust if needed

handlers:
  # Serve static files (CSS, JS, images) from the 'static' directory
  - url: /static
    static_dir: static
    secure: always

  # All other requests are handled by the Go application.
  # App Engine will build and run your main.go.
  - url: /.*
    script: _go_app # This special value tells App Engine to use the Go app
    secure: always

# Optional: Environment variables for your Go app
# env_variables:
#   MY_VARIABLE: "my_value"
