steps:
  # Step 1: Deploy to App Engine
  # gcloud app deploy will detect the Go runtime from app.yaml
  # and build the application before deploying.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'app'
      - 'deploy'
      - 'app.yaml' # Explicitly specify app.yaml
      - '--project=${PROJECT_ID}'
      - '--quiet'
      - '--promote'

# Optional: Set timeout for the build
timeout: '1200s' # Increased timeout slightly as Go builds can take a bit longer

# Optional: Specify which files trigger builds (if using Cloud Build triggers)
options:
  logging: CLOUD_LOGGING_ONLY
